language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode

env:
  - "HAML=1"
  - "NO_HAML=0"

gemfile:
  - Gemfile
  - test/ci/rails3_2.gemfile

matrix:
  exclude:
    - gemfile: Gemfile
      rvm: 1.8.7
      env: "HAML=1"
    - gemfile: Gemfile
      rvm: 1.8.7
      env: "NO_HAML=0"
    - gemfile: Gemfile
      rvm: jruby-18mode
      env: "HAML=1"
    - gemfile: Gemfile
      rvm: jruby-18mode
      env: "NO_HAML=0"
